services:
  - type: web
    name: starvantis-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        value: sqlite:///./starvantis.db
      - key: SECRET_KEY
        generateValue: true
      - key: NASA_API_KEY
        value: wxu9OqadiasUMrH5fC2NaF33AsXfLiQ7FCRsN2yH
    healthCheckPath: /health
