"""Initial Starvantis tables

Revision ID: 853a7cfd464e
Revises: 
Create Date: 2026-08-28 02:57:46.670235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853a7cfd464e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subsystem', sa.String(length=128), nullable=False),
    sa.Column('asset', sa.String(length=128), nullable=False),
    sa.Column('timestamp_str', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=128), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_acknowledged'), ['acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)

    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('satellite_id', sa.String(length=32), nullable=False),
    sa.Column('subsystem', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('radar_angle_deg', sa.Float(), nullable=False),
    sa.Column('radar_distance_ratio', sa.Float(), nullable=False),
    sa.Column('contributing_signals', sa.Text(), nullable=True),
    sa.Column('suggested_mitigation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_events_satellite_id'), ['satellite_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('conjunction_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('primary_satellite_id', sa.String(length=32), nullable=False),
    sa.Column('target_object_id', sa.String(length=64), nullable=False),
    sa.Column('target_name', sa.String(length=128), nullable=False),
    sa.Column('tca_time', sa.DateTime(), nullable=False),
    sa.Column('tca_formatted', sa.String(length=64), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('relative_velocity_kms', sa.Float(), nullable=False),
    sa.Column('collision_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('recommended_delta_v_ms', sa.Float(), nullable=False),
    sa.Column('burn_direction', sa.String(length=32), nullable=False),
    sa.Column('burn_execution_epoch', sa.String(length=64), nullable=True),
    sa.Column('projected_post_burn_miss_km', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('maneuver_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('analysis_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conjunction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conjunction_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conjunction_events_primary_satellite_id'), ['primary_satellite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conjunction_events_target_object_id'), ['target_object_id'], unique=False)

    op.create_table('orbital_objects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=True),
    sa.Column('inclination_deg', sa.Float(), nullable=True),
    sa.Column('velocity_kms', sa.Float(), nullable=True),
    sa.Column('eccentricity', sa.Float(), nullable=True),
    sa.Column('semi_major_axis_km', sa.Float(), nullable=True),
    sa.Column('estimated_diameter_min_m', sa.Float(), nullable=True),
    sa.Column('estimated_diameter_max_m', sa.Float(), nullable=True),
    sa.Column('is_potentially_hazardous', sa.Boolean(), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=True),
    sa.Column('close_approach_date', sa.String(length=64), nullable=True),
    sa.Column('orbiting_body', sa.String(length=32), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('pos_z', sa.Float(), nullable=False),
    sa.Column('extra_details', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orbital_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orbital_objects_id'), ['id'], unique=False)

    op.create_table('risk_incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('satellite_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('telemetry_health_score', sa.Float(), nullable=False),
    sa.Column('conjunction_threat_score', sa.Float(), nullable=False),
    sa.Column('space_weather_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_incidents_satellite_id'), ['satellite_id'], unique=False)

    op.create_table('satellites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('orbit_type', sa.String(length=64), nullable=False),
    sa.Column('altitude', sa.String(length=32), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=False),
    sa.Column('inclination', sa.String(length=32), nullable=False),
    sa.Column('velocity', sa.String(length=32), nullable=False),
    sa.Column('launch_date', sa.String(length=32), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ground_station', sa.String(length=64), nullable=False),
    sa.Column('wave_color', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satellites_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('access_level', sa.String(length=32), nullable=False),
    sa.Column('assigned_satellites', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('telemetry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=False),
    sa.Column('solar_power_kw', sa.Float(), nullable=False),
    sa.Column('temp_celsius', sa.Float(), nullable=False),
    sa.Column('bus_voltage', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=False),
    sa.Column('velocity_kms', sa.Float(), nullable=False),
    sa.Column('roll_deg', sa.Float(), nullable=False),
    sa.Column('pitch_deg', sa.Float(), nullable=False),
    sa.Column('yaw_deg', sa.Float(), nullable=False),
    sa.Column('signal_dbm', sa.Float(), nullable=False),
    sa.Column('tracked_objects', sa.Integer(), nullable=False),
    sa.Column('active_alerts', sa.Integer(), nullable=False),
    sa.Column('eps_health', sa.Integer(), nullable=False),
    sa.Column('adcs_health', sa.Integer(), nullable=False),
    sa.Column('ttc_health', sa.Integer(), nullable=False),
    sa.Column('payload_health', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomalous', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_records_satellite_id'), ['satellite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_records_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_records_satellite_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_records_id'))

    op.drop_table('telemetry_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satellites_id'))

    op.drop_table('satellites')
    with op.batch_alter_table('risk_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_incidents_satellite_id'))
        batch_op.drop_index(batch_op.f('ix_risk_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_risk_incidents_created_at'))

    op.drop_table('risk_incidents')
    with op.batch_alter_table('orbital_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orbital_objects_id'))

    op.drop_table('orbital_objects')
    with op.batch_alter_table('conjunction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conjunction_events_target_object_id'))
        batch_op.drop_index(batch_op.f('ix_conjunction_events_primary_satellite_id'))
        batch_op.drop_index(batch_op.f('ix_conjunction_events_id'))

    op.drop_table('conjunction_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_events_satellite_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_events_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_events_created_at'))

    op.drop_table('anomaly_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_asset'))
        batch_op.drop_index(batch_op.f('ix_alerts_acknowledged'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
