export interface SatelliteFleetDefinition {
  id: string;
  name: string;
  code: string;
  agency: string;
  type: string;
  role: string;
  orbitType: string;
  altitude: string;
  altitudeKm: number;
  inclination: string;
  velocity: string;
  launchDate: string;
  health: number;
  status: 'OPERATIONAL' | 'DEGRADED' | 'STANDBY';
  groundStation: string;
  signal: string;
  trackedObjects: number;
  activeAlerts: number;
  batteryVoltage: string;
  solarPower: string;
  temp: string;
  lat: string;
  lng: string;
  roll: string;
  pitch: string;
  yaw: string;
  waveColor: string;
  image: string;
  conjunctionTarget: {
    id: string;
    targetId: string;
    targetName: string;
    missDistanceKm: number;
    tca: string;
    pc: number;
    riskLevel: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
    recommendedBurn: string;
    deltaV: number;
    burnDirection: string;
    postBurnMissKm: number;
    crossingAngleDeg: number;
    approachVector: string;
    trajectoryType: 'polar-perpendicular' | 'retrograde-crosslink' | 'coplanar-overtake' | 'cislunar-hyperbolic' | 'lagrange-halo' | 'sso-descending';
  };
  telemetryMetrics: {
    batteryTemp: { current: number; baseline: number; deviation: string; status: 'nominal' | 'warning' | 'critical' };
    busVoltage: { current: number; baseline: number; deviation: string; status: 'nominal' | 'warning' | 'critical' };
    powerDraw: { current: number; baseline: number; deviation: string; status: 'nominal' | 'warning' | 'critical' };
    attitudeError: { current: number; baseline: number; deviation: string; status: 'nominal' | 'warning' | 'critical' };
    commsSnr: { current: number; baseline: number; deviation: string; status: 'nominal' | 'warning' | 'critical' };
  };
  riskBreakdown: {
    overallScore: number;
    status: 'CRITICAL' | 'ELEVATED' | 'NOMINAL';
    thermalRisk: number;
    conjunctionRisk: number;
    gyroDriftRisk: number;
    radiationRisk: number;
    summary: string;
  };
}

export const FLEET_SATELLITES: SatelliteFleetDefinition[] = [
  {
    id: 'CHANDRAYAAN-3',
    image: '/images/satellites/chandrayaan3.jpg',
    name: 'CHANDRAYAAN-3 ORBITER [PRASHAST]',
    code: 'CH-3',
    agency: 'ISRO',
    type: 'Lunar Polar Reconnaissance & Relay',
    role: 'Lunar Surface Topography & Relay Link',
    orbitType: 'Lunar Polar Orbit (LPO)',
    altitude: '100 km (Moon)',
    altitudeKm: 100,
    inclination: '90.00°',
    velocity: '1.63 km/s',
    launchDate: '2023-07-14',
    health: 99,
    status: 'OPERATIONAL',
    groundStation: 'ISTRAC (Byalalu DSN-32)',
    signal: '-68 dBm',
    trackedObjects: 18,
    activeAlerts: 0,
    batteryVoltage: '28.9 V',
    solarPower: '0.74 kW',
    temp: '-14.2 °C',
    lat: '89.2° S (Lunar Pole)',
    lng: '69.37° E',
    roll: '0.04°',
    pitch: '0.02°',
    yaw: '0.00°',
    waveColor: '#f59e0b',
    conjunctionTarget: {
      id: 'CONJ-LUNAR-01',
      targetId: 'LRO-DEBRIS #041',
      targetName: 'LUNAR RECONNAISSANCE PASS OBJECT #041',
      missDistanceKm: 4.2,
      tca: '14:22:10 UTC (in 02:45:12)',
      pc: 2.14e-5,
      riskLevel: 'LOW',
      recommendedBurn: 'Autonomous apolune phase trim +0.12 m/s prograde.',
      deltaV: 0.12,
      burnDirection: 'PROGRADE (+V)',
      postBurnMissKm: 28.5,
      crossingAngleDeg: 88,
      approachVector: 'POLAR_NORTH_SOUTH',
      trajectoryType: 'cislunar-hyperbolic',
    },
    telemetryMetrics: {
      batteryTemp: { current: 18.2, baseline: 18.0, deviation: '+0.2°C (+1.1%)', status: 'nominal' },
      busVoltage: { current: 28.9, baseline: 28.8, deviation: '+0.1V (+0.3%)', status: 'nominal' },
      powerDraw: { current: 310.0, baseline: 305.0, deviation: '+5W (+1.6%)', status: 'nominal' },
      attitudeError: { current: 0.006, baseline: 0.010, deviation: '-0.004°', status: 'nominal' },
      commsSnr: { current: 22.4, baseline: 20.0, deviation: '+2.4 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 14,
      status: 'NOMINAL',
      thermalRisk: 8,
      conjunctionRisk: 12,
      gyroDriftRisk: 5,
      radiationRisk: 22,
      summary: 'Lunar polar orbital parameters nominal. High telemetry SNR via 32-meter Deep Space Network antenna.',
    },
  },
  {
    id: 'ADITYA-L1',
    image: '/images/satellites/adityal1.jpg',
    name: 'ADITYA-L1 [SURYA-VEDH]',
    code: 'ADITYA-L1',
    agency: 'ISRO',
    type: 'Solar Corona & Space Weather Observatory',
    role: 'Coronal Mass Ejection & Solar Flare Early Warning',
    orbitType: 'Sun-Earth L1 Halo Orbit',
    altitude: '1.5M km (L1 Halo)',
    altitudeKm: 1500000,
    inclination: 'Halo-L1',
    velocity: '0.28 km/s',
    launchDate: '2023-09-02',
    health: 98,
    status: 'OPERATIONAL',
    groundStation: 'ISRO Telemetry (Bangalore / Goldstone)',
    signal: '-74 dBm',
    trackedObjects: 6,
    activeAlerts: 0,
    batteryVoltage: '28.8 V',
    solarPower: '1.85 kW',
    temp: '21.4 °C',
    lat: '0.0° N (L1 Point)',
    lng: '0.0° E',
    roll: '0.01°',
    pitch: '0.01°',
    yaw: '0.00°',
    waveColor: '#fbbf24',
    conjunctionTarget: {
      id: 'CONJ-L1-02',
      targetId: 'SOHO-DRIFT #009',
      targetName: 'SOLAR INTERPLANETARY DUST MONITOR #009',
      missDistanceKm: 14.8,
      tca: '19:40:00 UTC (in 08:12:00)',
      pc: 1.05e-6,
      riskLevel: 'LOW',
      recommendedBurn: 'No action required. Halo station-keeping thruster pulse scheduled at T+48h.',
      deltaV: 0.04,
      burnDirection: 'STATION_KEEPING',
      postBurnMissKm: 45.0,
      crossingAngleDeg: 35,
      approachVector: 'LAGRANGE_DRIFT',
      trajectoryType: 'lagrange-halo',
    },
    telemetryMetrics: {
      batteryTemp: { current: 21.4, baseline: 21.0, deviation: '+0.4°C (+1.9%)', status: 'nominal' },
      busVoltage: { current: 28.8, baseline: 28.8, deviation: '0.0V (0.0%)', status: 'nominal' },
      powerDraw: { current: 620.0, baseline: 615.0, deviation: '+5W (+0.8%)', status: 'nominal' },
      attitudeError: { current: 0.004, baseline: 0.005, deviation: '-0.001°', status: 'nominal' },
      commsSnr: { current: 19.5, baseline: 18.5, deviation: '+1.0 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 18,
      status: 'NOMINAL',
      thermalRisk: 14,
      conjunctionRisk: 4,
      gyroDriftRisk: 6,
      radiationRisk: 42,
      summary: 'VELC and SUIT payloads tracking active solar coronal mass ejections. Space weather stream verified.',
    },
  },
  {
    id: 'EOS-04',
    image: '/images/satellites/eos04.jpg',
    name: 'EOS-04 / RISAT-1A [SAR-BHARAT]',
    code: 'EOS-04',
    agency: 'ISRO',
    type: 'C-Band Synthetic Aperture Radar (SAR)',
    role: 'All-Weather Day-Night Earth Observation',
    orbitType: 'Sun-Synchronous Polar Orbit (SSO)',
    altitude: '529 km',
    altitudeKm: 529,
    inclination: '97.50°',
    velocity: '7.60 km/s',
    launchDate: '2022-02-14',
    health: 96,
    status: 'OPERATIONAL',
    groundStation: 'NRSC Shadnagar (Hyderabad)',
    signal: '-62 dBm',
    trackedObjects: 142,
    activeAlerts: 1,
    batteryVoltage: '28.2 V',
    solarPower: '2.40 kW',
    temp: '23.8 °C',
    lat: '21.145° N',
    lng: '79.088° E',
    roll: '0.8°',
    pitch: '-0.4°',
    yaw: '92.1°',
    waveColor: '#38bdf8',
    conjunctionTarget: {
      id: 'CONJ-SAR-89',
      targetId: 'COSMOS-1408 #4982',
      targetName: 'COSMOS 1408 ASAT DEBRIS FRAGMENT #4982',
      missDistanceKm: 1.85,
      tca: '17:15:32 UTC (in 02:30:14)',
      pc: 1.62e-4,
      riskLevel: 'CRITICAL',
      recommendedBurn: 'Execute +0.36 m/s radial cross-track evasive burn at ascending node.',
      deltaV: 0.36,
      burnDirection: 'RADIAL (+R)',
      postBurnMissKm: 19.8,
      crossingAngleDeg: 104,
      approachVector: 'DESCENDING_POLAR_INTERSECT',
      trajectoryType: 'sso-descending',
    },
    telemetryMetrics: {
      batteryTemp: { current: 31.5, baseline: 24.0, deviation: '+7.5°C (+31.2%)', status: 'warning' },
      busVoltage: { current: 27.6, baseline: 28.0, deviation: '-0.4V (-1.4%)', status: 'nominal' },
      powerDraw: { current: 1450.0, baseline: 1420.0, deviation: '+30W (+2.1%)', status: 'nominal' },
      attitudeError: { current: 0.028, baseline: 0.015, deviation: '+0.013°', status: 'warning' },
      commsSnr: { current: 21.0, baseline: 22.0, deviation: '-1.0 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 68,
      status: 'CRITICAL',
      thermalRisk: 48,
      conjunctionRisk: 84,
      gyroDriftRisk: 34,
      radiationRisk: 26,
      summary: 'Active critical conjunction detected with Cosmos 1408 debris. Radar antenna thermal load elevated during SAR pulse.',
    },
  },
  {
    id: 'CARTOSAT-3',
    image: '/images/satellites/cartosat3.jpg',
    name: 'CARTOSAT-3 [NAVDARSHAK-3]',
    code: 'CARTO-3',
    agency: 'ISRO',
    type: 'Sub-Meter Panchromatic Optical Imaging',
    role: 'Precision High-Resolution Cartography & Defense',
    orbitType: 'Sun-Synchronous Polar Orbit (SSO)',
    altitude: '505 km',
    altitudeKm: 505,
    inclination: '97.40°',
    velocity: '7.62 km/s',
    launchDate: '2019-11-27',
    health: 95,
    status: 'OPERATIONAL',
    groundStation: 'ISTRAC Ground Station (Bangalore)',
    signal: '-59 dBm',
    trackedObjects: 188,
    activeAlerts: 1,
    batteryVoltage: '28.5 V',
    solarPower: '2.10 kW',
    temp: '22.1 °C',
    lat: '28.613° N',
    lng: '77.209° E',
    roll: '1.4°',
    pitch: '0.2°',
    yaw: '88.5°',
    waveColor: '#10b981',
    conjunctionTarget: {
      id: 'CONJ-CARTO-44',
      targetId: 'FENGYUN-1C #1904',
      targetName: 'FENGYUN 1C HIGH-VELOCITY DEBRIS #1904',
      missDistanceKm: 2.4,
      tca: '18:04:12 UTC (in 03:18:54)',
      pc: 1.18e-4,
      riskLevel: 'HIGH',
      recommendedBurn: 'Execute +0.28 m/s retrograde burn to expand radial separation.',
      deltaV: 0.28,
      burnDirection: 'RETROGRADE (-V)',
      postBurnMissKm: 22.4,
      crossingAngleDeg: 122,
      approachVector: 'POLAR_RETROGRADE_CROSSING',
      trajectoryType: 'retrograde-crosslink',
    },
    telemetryMetrics: {
      batteryTemp: { current: 24.8, baseline: 23.0, deviation: '+1.8°C (+7.8%)', status: 'nominal' },
      busVoltage: { current: 28.3, baseline: 28.0, deviation: '+0.3V (+1.1%)', status: 'nominal' },
      powerDraw: { current: 680.0, baseline: 650.0, deviation: '+30W (+4.6%)', status: 'nominal' },
      attitudeError: { current: 0.018, baseline: 0.012, deviation: '+0.006°', status: 'nominal' },
      commsSnr: { current: 26.2, baseline: 25.0, deviation: '+1.2 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 54,
      status: 'ELEVATED',
      thermalRisk: 22,
      conjunctionRisk: 72,
      gyroDriftRisk: 18,
      radiationRisk: 20,
      summary: 'Sub-meter optical telescope active. Evasive orbit trim burn calculated to bypass Fengyun 1C debris track.',
    },
  },
  {
    id: 'INSAT-3DR',
    image: '/images/satellites/insat3dr.jpg',
    name: 'INSAT-3DR [MEGHDOOT-MET]',
    code: 'INSAT-3DR',
    agency: 'ISRO',
    type: 'Geostationary Meteorological Imager & Sounder',
    role: 'Cyclone Tracking, Weather Forecasting & SAR Transponder',
    orbitType: 'Geostationary Orbit (GEO 74°E)',
    altitude: '35,786 km',
    altitudeKm: 35786,
    inclination: '0.05°',
    velocity: '3.07 km/s',
    launchDate: '2016-09-08',
    health: 94,
    status: 'OPERATIONAL',
    groundStation: 'Master Control Facility (Hassan, Karnataka)',
    signal: '-65 dBm',
    trackedObjects: 42,
    activeAlerts: 0,
    batteryVoltage: '28.1 V',
    solarPower: '1.70 kW',
    temp: '18.6 °C',
    lat: '0.02° N',
    lng: '74.00° E (GEO Slot)',
    roll: '0.02°',
    pitch: '0.01°',
    yaw: '0.00°',
    waveColor: '#06b6d4',
    conjunctionTarget: {
      id: 'CONJ-GEO-12',
      targetId: 'INTELSAT-DEAD #088',
      targetName: 'DECOMMISSIONED INTELSAT DRIFT OBJECT #088',
      missDistanceKm: 7.9,
      tca: '22:10:00 UTC (in 07:24:42)',
      pc: 3.40e-5,
      riskLevel: 'LOW',
      recommendedBurn: 'Execute standard +0.08 m/s east-west longitude station-keeping.',
      deltaV: 0.08,
      burnDirection: 'EAST-WEST TRIM',
      postBurnMissKm: 38.0,
      crossingAngleDeg: 12,
      approachVector: 'COPLANAR_GEO_OVERTAKE',
      trajectoryType: 'coplanar-overtake',
    },
    telemetryMetrics: {
      batteryTemp: { current: 19.5, baseline: 19.0, deviation: '+0.5°C (+2.6%)', status: 'nominal' },
      busVoltage: { current: 28.0, baseline: 28.0, deviation: '0.0V (0.0%)', status: 'nominal' },
      powerDraw: { current: 540.0, baseline: 530.0, deviation: '+10W (+1.9%)', status: 'nominal' },
      attitudeError: { current: 0.010, baseline: 0.010, deviation: '0.000°', status: 'nominal' },
      commsSnr: { current: 24.5, baseline: 23.0, deviation: '+1.5 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 21,
      status: 'NOMINAL',
      thermalRisk: 12,
      conjunctionRisk: 28,
      gyroDriftRisk: 8,
      radiationRisk: 32,
      summary: 'Multispectral meteorological radiometer and sounder active. Cyclone surveillance stream nominal.',
    },
  },
  {
    id: 'OCEANSAT-3',
    image: '/images/satellites/oceansat3.jpg',
    name: 'OCEANSAT-3 / EOS-06 [SAMUDRA-NETRA]',
    code: 'EOS-06',
    agency: 'ISRO',
    type: 'Ocean Color Monitor & Scatterometer',
    role: 'Maritime Security, Chlorophyll Density & Sea-Surface Winds',
    orbitType: 'Sun-Synchronous Polar Orbit (SSO)',
    altitude: '720 km',
    altitudeKm: 720,
    inclination: '98.28°',
    velocity: '7.49 km/s',
    launchDate: '2022-11-26',
    health: 98,
    status: 'OPERATIONAL',
    groundStation: 'NRSC (Hyderabad / Antarctica Bharti)',
    signal: '-60 dBm',
    trackedObjects: 110,
    activeAlerts: 0,
    batteryVoltage: '28.7 V',
    solarPower: '2.35 kW',
    temp: '20.2 °C',
    lat: '15.299° N',
    lng: '74.124° E',
    roll: '0.5°',
    pitch: '-0.2°',
    yaw: '90.4°',
    waveColor: '#0284c7',
    conjunctionTarget: {
      id: 'CONJ-OCEAN-31',
      targetId: 'SL-8-DEBRIS #1128',
      targetName: 'COSMOS 3M SPENT STAGE DEBRIS #1128',
      missDistanceKm: 5.1,
      tca: '20:18:40 UTC (in 05:33:22)',
      pc: 5.80e-5,
      riskLevel: 'MEDIUM',
      recommendedBurn: 'Execute +0.16 m/s inclination trim at orbital node.',
      deltaV: 0.16,
      burnDirection: 'INCLINATION TRIM (+W)',
      postBurnMissKm: 26.5,
      crossingAngleDeg: 78,
      approachVector: 'POLAR_OBLIQUE_INTERSECT',
      trajectoryType: 'polar-perpendicular',
    },
    telemetryMetrics: {
      batteryTemp: { current: 20.8, baseline: 20.0, deviation: '+0.8°C (+4.0%)', status: 'nominal' },
      busVoltage: { current: 28.6, baseline: 28.5, deviation: '+0.1V (+0.4%)', status: 'nominal' },
      powerDraw: { current: 890.0, baseline: 880.0, deviation: '+10W (+1.1%)', status: 'nominal' },
      attitudeError: { current: 0.014, baseline: 0.012, deviation: '+0.002°', status: 'nominal' },
      commsSnr: { current: 23.8, baseline: 22.5, deviation: '+1.3 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 24,
      status: 'NOMINAL',
      thermalRisk: 16,
      conjunctionRisk: 34,
      gyroDriftRisk: 14,
      radiationRisk: 22,
      summary: 'Ku-band scatterometer and thermal infrared sensor delivering high-precision ocean surface vectors.',
    },
  },
  {
    id: 'GAGANYAAN-G1',
    image: '/images/satellites/gaganyaan.jpg',
    name: 'GAGANYAAN-G1 [VYOM-ORBITER]',
    code: 'GAGAN-G1',
    agency: 'ISRO',
    type: 'Human-Rated Orbital Module Path-Finder',
    role: 'Life Support, Thermal Protection & Precision Re-Entry Validation',
    orbitType: 'Low Earth Orbit (LEO 400 km)',
    altitude: '400 km',
    altitudeKm: 400,
    inclination: '51.60°',
    velocity: '7.67 km/s',
    launchDate: '2024-12-20',
    health: 99,
    status: 'OPERATIONAL',
    groundStation: 'Satish Dhawan Space Centre (Sriharikota)',
    signal: '-54 dBm',
    trackedObjects: 224,
    activeAlerts: 1,
    batteryVoltage: '28.9 V',
    solarPower: '3.20 kW',
    temp: '21.0 °C',
    lat: '13.719° N',
    lng: '80.230° E',
    roll: '0.2°',
    pitch: '0.0°',
    yaw: '0.0°',
    waveColor: '#ef4444',
    conjunctionTarget: {
      id: 'CONJ-GAGAN-01',
      targetId: 'CZ-3B-DEBRIS #8892',
      targetName: 'UPPER STAGE ORBITAL DEBRIS #8892',
      missDistanceKm: 1.1,
      tca: '16:48:22 UTC (in 02:03:04)',
      pc: 2.85e-4,
      riskLevel: 'CRITICAL',
      recommendedBurn: 'Execute automated +0.55 m/s emergency collision avoidance maneuver (CAM).',
      deltaV: 0.55,
      burnDirection: 'RETROGRADE (-V)',
      postBurnMissKm: 24.8,
      crossingAngleDeg: 110,
      approachVector: 'EQUATORIAL_CROSS_TRACK',
      trajectoryType: 'retrograde-crosslink',
    },
    telemetryMetrics: {
      batteryTemp: { current: 22.0, baseline: 21.0, deviation: '+1.0°C (+4.8%)', status: 'nominal' },
      busVoltage: { current: 28.9, baseline: 29.0, deviation: '-0.1V (-0.3%)', status: 'nominal' },
      powerDraw: { current: 1250.0, baseline: 1200.0, deviation: '+50W (+4.2%)', status: 'nominal' },
      attitudeError: { current: 0.008, baseline: 0.008, deviation: '0.000°', status: 'nominal' },
      commsSnr: { current: 27.5, baseline: 26.0, deviation: '+1.5 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 72,
      status: 'CRITICAL',
      thermalRisk: 28,
      conjunctionRisk: 92,
      gyroDriftRisk: 12,
      radiationRisk: 18,
      summary: 'Human-rated ECLSS telemetry nominal. Immediate CAM burn authorization required for CZ-3B debris evasion.',
    },
  },
  {
    id: 'SENTINEL-6A',
    image: '/images/satellites/sentinel6a.jpg',
    name: 'SENTINEL-6A [MICHAEL-FREILICH]',
    code: 'SNTL-6A',
    agency: 'NASA / ESA / NOAA',
    type: 'Radar Altimetry & Ocean Surface Topography',
    role: 'Global Sea-Level Sentinel & Climate Monitoring',
    orbitType: 'Non-Sun-Synchronous LEO',
    altitude: '1,336 km',
    altitudeKm: 1336,
    inclination: '66.04°',
    velocity: '7.20 km/s',
    launchDate: '2020-11-21',
    health: 98,
    status: 'OPERATIONAL',
    groundStation: 'Kiruna / Fairbanks (NASA/ESA)',
    signal: '-65 dBm',
    trackedObjects: 128,
    activeAlerts: 2,
    batteryVoltage: '28.4 V',
    solarPower: '1.82 kW',
    temp: '22.6 °C',
    lat: '12.456° N',
    lng: '77.123° E',
    roll: '1.2°',
    pitch: '-0.6°',
    yaw: '89.3°',
    waveColor: '#63c7ff',
    conjunctionTarget: {
      id: 'CONJ-8821',
      targetId: 'DEB-3842',
      targetName: 'COSMOS 2251 DEBRIS #3842',
      missDistanceKm: 1.2,
      tca: '18:53:21 UTC (in 04:21:16)',
      pc: 1.84e-4,
      riskLevel: 'CRITICAL',
      recommendedBurn: 'Execute +0.42 m/s retrograde burn at apogee node.',
      deltaV: 0.42,
      burnDirection: 'RETROGRADE (-V)',
      postBurnMissKm: 18.6,
      crossingAngleDeg: 95,
      approachVector: 'POLAR_ORTHOGONAL',
      trajectoryType: 'polar-perpendicular',
    },
    telemetryMetrics: {
      batteryTemp: { current: 41.2, baseline: 26.8, deviation: '+14.4°C (+53.7%)', status: 'critical' },
      busVoltage: { current: 26.4, baseline: 28.1, deviation: '-1.7V (-6.0%)', status: 'warning' },
      powerDraw: { current: 482.0, baseline: 420.0, deviation: '+62W (+14.8%)', status: 'warning' },
      attitudeError: { current: 0.042, baseline: 0.025, deviation: '+0.017°', status: 'nominal' },
      commsSnr: { current: 18.4, baseline: 19.5, deviation: '-1.1 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 78,
      status: 'CRITICAL',
      thermalRisk: 86,
      conjunctionRisk: 88,
      gyroDriftRisk: 28,
      radiationRisk: 22,
      summary: 'Battery Cell 3 Thermal Runaway detected concurrently with high-probability Cosmos 2251 conjunction.',
    },
  },
  {
    id: 'STARLINK-4012',
    image: '/images/satellites/starlink.jpg',
    name: 'STARLINK-4012 [LASER-CROSSLINK]',
    code: 'SL-4012',
    agency: 'SpaceX',
    type: 'High-Throughput Optical Space Laser Relay',
    role: 'Low-Latency Inter-Satellite Crosslink Backbone',
    orbitType: 'LEO (High Inclination)',
    altitude: '550 km',
    altitudeKm: 550,
    inclination: '53.20°',
    velocity: '7.59 km/s',
    launchDate: '2023-11-04',
    health: 99,
    status: 'OPERATIONAL',
    groundStation: 'Svalbard / Starlink Gateway',
    signal: '-58 dBm',
    trackedObjects: 94,
    activeAlerts: 0,
    batteryVoltage: '28.8 V',
    solarPower: '2.14 kW',
    temp: '19.4 °C',
    lat: '34.052° N',
    lng: '-118.243° W',
    roll: '0.4°',
    pitch: '0.1°',
    yaw: '142.1°',
    waveColor: '#10b981',
    conjunctionTarget: {
      id: 'CONJ-4102',
      targetId: 'DEB-4102',
      targetName: 'FENGYUN 1C FRAGMENT #4102',
      missDistanceKm: 6.8,
      tca: '21:14:08 UTC (in 06:42:03)',
      pc: 4.12e-5,
      riskLevel: 'MEDIUM',
      recommendedBurn: 'Execute +0.18 m/s out-of-plane cross-track burn.',
      deltaV: 0.18,
      burnDirection: 'OUT-OF-PLANE (+W)',
      postBurnMissKm: 24.5,
      crossingAngleDeg: 64,
      approachVector: 'MID_INCLINATION_OBLIQUE',
      trajectoryType: 'polar-perpendicular',
    },
    telemetryMetrics: {
      batteryTemp: { current: 24.2, baseline: 25.0, deviation: '-0.8°C (-3.2%)', status: 'nominal' },
      busVoltage: { current: 28.2, baseline: 28.0, deviation: '+0.2V (+0.7%)', status: 'nominal' },
      powerDraw: { current: 510.0, baseline: 505.0, deviation: '+5W (+0.9%)', status: 'nominal' },
      attitudeError: { current: 0.012, baseline: 0.020, deviation: '-0.008°', status: 'nominal' },
      commsSnr: { current: 24.8, baseline: 22.0, deviation: '+2.8 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 19,
      status: 'NOMINAL',
      thermalRisk: 12,
      conjunctionRisk: 26,
      gyroDriftRisk: 8,
      radiationRisk: 18,
      summary: 'Inter-satellite laser terminals locked. Zero active thermal or power bus anomalies.',
    },
  },
  {
    id: 'NOAA-20',
    image: '/images/satellites/noaa20.jpg',
    name: 'NOAA-20 / JPSS-1 [MET-SENTINEL]',
    code: 'NOAA-20',
    agency: 'NOAA / NASA',
    type: 'Hyperspectral JPSS Polar Weather Sentinel',
    role: 'Global Atmospheric Sounding & Severe Storm Prediction',
    orbitType: 'Sun-Synchronous Polar Orbit (SSO)',
    altitude: '824 km',
    altitudeKm: 824,
    inclination: '98.70°',
    velocity: '7.44 km/s',
    launchDate: '2017-11-18',
    health: 91,
    status: 'DEGRADED',
    groundStation: 'Svalbard / McMurdo Station',
    signal: '-81 dBm',
    trackedObjects: 210,
    activeAlerts: 3,
    batteryVoltage: '26.4 V',
    solarPower: '1.42 kW',
    temp: '38.6 °C',
    lat: '51.507° N',
    lng: '-0.127° W',
    roll: '3.4°',
    pitch: '-2.1°',
    yaw: '210.5°',
    waveColor: '#f59e0b',
    conjunctionTarget: {
      id: 'CONJ-6109',
      targetId: 'DEB-6109',
      targetName: 'CZ-4B SPENT STAGE DEBRIS #6109',
      missDistanceKm: 0.85,
      tca: '15:20:10 UTC (in 00:48:05)',
      pc: 3.42e-4,
      riskLevel: 'CRITICAL',
      recommendedBurn: 'Execute emergency +0.65 m/s radial orbit separation burn.',
      deltaV: 0.65,
      burnDirection: 'RADIAL (+R)',
      postBurnMissKm: 16.2,
      crossingAngleDeg: 140,
      approachVector: 'HEAD_ON_RETROGRADE',
      trajectoryType: 'retrograde-crosslink',
    },
    telemetryMetrics: {
      batteryTemp: { current: 38.6, baseline: 25.0, deviation: '+13.6°C (+54.4%)', status: 'critical' },
      busVoltage: { current: 25.8, baseline: 28.0, deviation: '-2.2V (-7.8%)', status: 'critical' },
      powerDraw: { current: 520.0, baseline: 410.0, deviation: '+110W (+26.8%)', status: 'critical' },
      attitudeError: { current: 0.082, baseline: 0.020, deviation: '+0.062°', status: 'critical' },
      commsSnr: { current: 12.4, baseline: 18.0, deviation: '-5.6 dB', status: 'critical' },
    },
    riskBreakdown: {
      overallScore: 89,
      status: 'CRITICAL',
      thermalRisk: 92,
      conjunctionRisk: 96,
      gyroDriftRisk: 82,
      radiationRisk: 38,
      summary: 'Cryogenic cooler vibration causing attitude gyro drift and extreme head-on collision threat.',
    },
  },
  {
    id: 'JWST',
    image: '/images/satellites/jwst.jpg',
    name: 'JWST [JAMES-WEBB-DEEP-SPACE]',
    code: 'JWST',
    agency: 'NASA / ESA / CSA',
    type: 'Infrared Deep-Space Space Observatory',
    role: 'Exoplanet Spectroscopy & Deep Universe Reconnaissance',
    orbitType: 'Sun-Earth L2 Halo Orbit',
    altitude: '1.5M km (L2 Halo)',
    altitudeKm: 1500000,
    inclination: 'Halo-L2',
    velocity: '0.22 km/s',
    launchDate: '2021-12-25',
    health: 97,
    status: 'OPERATIONAL',
    groundStation: 'Deep Space Network (Goldstone / Madrid)',
    signal: '-61 dBm',
    trackedObjects: 38,
    activeAlerts: 1,
    batteryVoltage: '29.2 V',
    solarPower: '3.45 kW',
    temp: '16.8 °C',
    lat: '0.042° N',
    lng: '-75.201° W',
    roll: '0.1°',
    pitch: '0.0°',
    yaw: '180.0°',
    waveColor: '#ec4899',
    conjunctionTarget: {
      id: 'CONJ-0812',
      targetId: 'DEB-0812',
      targetName: 'THOR-ABLE APOGEE MOTOR DEBRIS #0812',
      missDistanceKm: 8.4,
      tca: '23:45:00 UTC (in 09:12:55)',
      pc: 1.25e-5,
      riskLevel: 'LOW',
      recommendedBurn: 'No burn required. Natural orbital precession expands separation.',
      deltaV: 0.05,
      burnDirection: 'NOMINAL DRIFT',
      postBurnMissKm: 32.0,
      crossingAngleDeg: 24,
      approachVector: 'HEO_APOGEE_PASS',
      trajectoryType: 'cislunar-hyperbolic',
    },
    telemetryMetrics: {
      batteryTemp: { current: 18.4, baseline: 18.0, deviation: '+0.4°C (+2.2%)', status: 'nominal' },
      busVoltage: { current: 29.0, baseline: 29.0, deviation: '0.0V (0.0%)', status: 'nominal' },
      powerDraw: { current: 780.0, baseline: 760.0, deviation: '+20W (+2.6%)', status: 'nominal' },
      attitudeError: { current: 0.008, baseline: 0.010, deviation: '-0.002°', status: 'nominal' },
      commsSnr: { current: 28.5, baseline: 26.0, deviation: '+2.5 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 26,
      status: 'NOMINAL',
      thermalRisk: 15,
      conjunctionRisk: 18,
      gyroDriftRisk: 10,
      radiationRisk: 48,
      summary: 'Sunshield deployed nominal. Cryogenic Mid-Infrared Instrument (MIRI) operating at 7 Kelvin.',
    },
  },
  {
    id: 'LANDSAT-9',
    image: '/images/satellites/landsat9.jpg',
    name: 'LANDSAT-9 [THERMAL-SENTINEL]',
    code: 'LAND-9',
    agency: 'USGS / NASA',
    type: 'High-Resolution Multispectral & Thermal Infrared',
    role: 'Global Land Surface & Geothermal Early Warning',
    orbitType: 'Sun-Synchronous Polar Orbit (SSO)',
    altitude: '705 km',
    altitudeKm: 705,
    inclination: '98.20°',
    velocity: '7.50 km/s',
    launchDate: '2021-09-27',
    health: 96,
    status: 'OPERATIONAL',
    groundStation: 'USGS EROS / Hartebeesthoek',
    signal: '-68 dBm',
    trackedObjects: 142,
    activeAlerts: 1,
    batteryVoltage: '28.1 V',
    solarPower: '1.95 kW',
    temp: '21.0 °C',
    lat: '-33.868° S',
    lng: '151.209° E',
    roll: '-0.8°',
    pitch: '0.4°',
    yaw: '95.2°',
    waveColor: '#a855f7',
    conjunctionTarget: {
      id: 'CONJ-2291',
      targetId: 'DEB-2291',
      targetName: 'TITAN 3C TRANSTAGE FRAGMENT #2291',
      missDistanceKm: 2.1,
      tca: '17:40:15 UTC (in 03:08:10)',
      pc: 1.15e-4,
      riskLevel: 'HIGH',
      recommendedBurn: 'Execute +0.38 m/s retrograde burn at descending node.',
      deltaV: 0.38,
      burnDirection: 'RETROGRADE (-V)',
      postBurnMissKm: 19.4,
      crossingAngleDeg: 115,
      approachVector: 'POLAR_OBLIQUE_SOUTH',
      trajectoryType: 'sso-descending',
    },
    telemetryMetrics: {
      batteryTemp: { current: 22.5, baseline: 21.0, deviation: '+1.5°C (+7.1%)', status: 'nominal' },
      busVoltage: { current: 27.9, baseline: 28.0, deviation: '-0.1V (-0.4%)', status: 'nominal' },
      powerDraw: { current: 460.0, baseline: 450.0, deviation: '+10W (+2.2%)', status: 'nominal' },
      attitudeError: { current: 0.022, baseline: 0.020, deviation: '+0.002°', status: 'nominal' },
      commsSnr: { current: 19.8, baseline: 20.0, deviation: '-0.2 dB', status: 'nominal' },
    },
    riskBreakdown: {
      overallScore: 46,
      status: 'ELEVATED',
      thermalRisk: 38,
      conjunctionRisk: 62,
      gyroDriftRisk: 24,
      radiationRisk: 22,
      summary: 'Thermal Infrared Sensor-2 (TIRS-2) nominal. Conjunction warning active with Titan 3C rocket debris fragment.',
    },
  },
];
